### ISSUE TITLE
Build failed: demo:android - A problem occurred evaluating project ':app'.

### ISSUE THREAD

**Issue by jonwhittlestone** [mess110/glassic#1]
Hi,

Unable to demo app for android with

`npm run demo:android` I also tried it with `sudo` as I sometimes get permission errors with npm.

Here's my log. Thanks

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'demo:android' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'predemo:android', 'demo:android', 'postdemo:android' ]
5 info predemo:android glassic@1.0.0
6 info demo:android glassic@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info glassic@1.0.0 Failed to exec demo:android script
9 verbose stack Error: glassic@1.0.0 demo:android: `npm run compile:android && npm run help:apk`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid glassic@1.0.0
11 verbose cwd /Users/jonwhittlestone/Downloads/ComplyAdvantage-glassic
12 error Darwin 15.0.0
13 error argv "node" "/usr/local/bin/npm" "run" "demo:android"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error glassic@1.0.0 demo:android: `npm run compile:android && npm run help:apk`
17 error Exit status 1
18 error Failed at the glassic@1.0.0 demo:android script 'npm run compile:android && npm run help:apk'.
18 error This is most likely a problem with the glassic package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run compile:android && npm run help:apk
18 error You can get their info via:
18 error     npm owner ls glassic
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by mess110** [comment]
Hi jonwhittlestone,

Thanks for your interest.

To demo the android app you need android development tools installed (or at least the build tools).

I intend to make a service which builds the applications for you, for all platforms. Stick around for updates :)

mess110

**Comment by mess110** [comment]
The build service for android and desktop is live http://mess110.github.com/glassic
